name: Checkstyle Compliance

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Repository
        uses: actions/checkout@v4
        
      - name: Checkstyle (PR-Review Reporter)
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .github/workflows/config/checkstyle.xml
          checkstyle_version: 10.12.5
          reporter: github-pr-review
        
      - name: Checkstyle (PR-Check Reporter)
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .github/workflows/config/checkstyle.xml
          checkstyle_version: 10.12.5
          reporter: github-pr-check
          level: error
